### PR TITLE
Emiel purescript 0.14

### PR DESCRIPTION
**Pull request by icyrockcom**
I've successfully run:

```
./bin/run-in-docker.sh hello-world ~/purescript/purescript-exercism/exercises/practice/hello-world/ /tmp
```

and got this `result.json`:

```
{
  "version": 1,
  "status": "fail",
  "message": "[info] Build succeeded.\n[warn] None of your project files import modules from some projects that are in the direct dependencies of your project.\nThese dependencies are unused. To fix this warning, remove the following packages from the list of dependencies in your config:\n- arrays\n- console\n- datetime\n- either\n- enums\n- foldable-traversable\n- integers\n- lists\n- math\n- maybe\n- ordered-collections\n- partial\n- strings\n- tuples\n- unfoldable\n- unicode\n- Suite: HelloWorld.helloWorld\n  ☠ Failed: Hello, World! because expected \"Hello, World!\", got \"Goodbye, Mars!\"\n\n1 test failed:\n\nIn \"HelloWorld.helloWorld\":\n  In \"Hello, World!\":\nError: Error: expected \"Hello, World!\", got \"Goodbye, Mars!\"\n\n[error] Tests failed: exit code: 1"
}
```

This looks expected.

Let me know if there's anything else that needs to be updated or looked at.

Just noticed this was your personal copy - let me know if I should instead make a PR to https://github.com/exercism/purescript-test-runner.

### CODE REVIEW

**Comment by icyrockcom** [comment]
@emiel Just wanted to check if you had a chance to look at this PR.

**Comment by emiel** [comment]
Sorry @icyrockcom. :/ I'm a bit swamped at the moment.

The more I think about the dependencies the more I think we should just align them all. A basic set from the https://github.com/purescript organization should be sufficient (i.e. not from purescript-contrib).

**Comment by icyrockcom** [comment]
> Sorry @icyrockcom. :/ I'm a bit swamped at the moment.

No worries, whenever you get a chance - I just wanted to make sure you did not miss the alert.

> The more I think about the dependencies the more I think we should just align them all. 

Not sure what you meant by this - can you clarify?

> A basic set from the https://github.com/purescript organization should be sufficient (i.e. not from purescript-contrib).

Are we using something from purescript-contrib at the moment?

As an aside, if this looks good, I think it makes sense to push it regardless of the other points and then do the other points in another iteration. We'd be still making progress.

**Comment by icyrockcom** [comment]
@emiel I know it's been a while, wanted to check if you had a chance to look into this.

**Comment by icyrockcom** [comment]
Pinging @ErikSchierboom as well in case @emiel is still swamped.

**Comment by ErikSchierboom** [comment]
@emiel Could you open a PR to the `exercism/purescript-test-runner` repo? That makes reviewing and testing slightly easier

**Comment by icyrockcom** [comment]
@ErikSchierboom I can push commits in this PR to `exercism/purescript-test-runner` if @emiel is busy - fine with you?

**Comment by ErikSchierboom** [comment]
Yep!

**Comment by icyrockcom** [comment]
@ErikSchierboom Done, let me know https://github.com/exercism/purescript-test-runner/pull/33

**Pull request closed without merging**
